name: nx_flutter_app
description: NX Flutter App.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.6
  dio: ^4.0.6
  provider: ^6.0.3
  intl: ^0.17.0
  sqflite: ^2.0.3
  path: ^1.8.1
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  openapi:
    path: ../api
  signature: ^5.2.1
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.4.0
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  firebase_messaging: ^12.0.3
  firebase_storage: ^10.3.7
  connectivity_plus: ^2.3.6+1
  internet_connection_checker: ^0.0.1+4
  flutter_background_service: ^2.1.3
  flutter_background_service_android: ^2.0.3
  fl_chart: ^0.55.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    